package com.glyphvisualizer;

/**
 * On-device drum classifier: given the squared-magnitude (power) spectrum at an onset frame,
 * predicts KICK / SNARE / HIHAT with a small MLP ({@code 29 -> 96 -> 48 -> 3}).
 *
 * <p>This replaces the old "compare scaled band-energy diffs" heuristic in {@link BeatDetector}.
 * The onset *detection* (complex spectral flux + peak-picking) is unchanged and still decides
 * *when* a hit happens; this only decides *what* it was, from the spectral envelope -- which is
 * what the ear keys on, so it's the part a learned model genuinely improves.
 *
 * <p>The weights live in {@link DrumClassifierModel} (generated by
 * {@code tool/train_drum_classifier.py}, trained across a wide range of synthetic drums + heavy
 * augmentation). The feature extraction and forward pass here are an exact mirror of that trainer's
 * Python; {@code DrumClassifierTest} locks the two together with golden vectors. All math
 * accumulates in {@code double} to match the trainer.
 *
 * <p><b>Latency:</b> the net is a few thousand MACs and runs only once per onset (no temporal
 * buffering, no per-frame inference), so a {@link #classify} call is microseconds and the hot path
 * allocates nothing -- it reuses the instance scratch buffers. {@code DrumClassifierLatencyTest}
 * guards that it stays fast.
 */
public final class DrumClassifier {

    public static final int KICK = 0;
    public static final int SNARE = 1;
    public static final int HIHAT = 2;

    // Per-instance scratch, reused every call so the hot path is allocation-free.
    private final float[] featBuf = new float[DrumClassifierModel.FEATURE_DIM];
    private final double[] stdFeat = new double[DrumClassifierModel.FEATURE_DIM];
    private final double[] hidden1 = new double[DrumClassifierModel.HIDDEN1];
    private final double[] hidden2 = new double[DrumClassifierModel.HIDDEN2];
    private final double[] logits = new double[DrumClassifierModel.NUM_CLASSES];

    /** Softmax probability of the winning class from the last {@link #classify} call (0..1). */
    public double lastConfidence = 0;

    /**
     * Classify an onset from its power spectrum.
     *
     * @param magnitude  squared-magnitude bins from {@code FFT.magnitude} (length >= NUM_BINS)
     * @param sampleRate the active capture sample rate (44100 / 48000)
     * @return {@link #KICK}, {@link #SNARE}, or {@link #HIHAT}; {@link #lastConfidence} is also set
     */
    public int classify(float[] magnitude, int sampleRate) {
        extractFeatures(magnitude, sampleRate, featBuf);
        forward(featBuf, stdFeat, hidden1, hidden2, logits);

        int best = 0;
        double max = logits[0];
        for (int c = 1; c < logits.length; c++) {
            if (logits[c] > max) {
                max = logits[c];
                best = c;
            }
        }
        double sum = 0;
        for (int c = 0; c < logits.length; c++) {
            sum += Math.exp(logits[c] - max);
        }
        lastConfidence = 1.0 / sum;   // softmax of the winner
        return best;
    }

    // ------------------------------------------------------------------------------------
    // Feature extraction -- exact mirror of extract_features() in tool/train_drum_classifier.py.
    // 24 loudness-invariant log-band features (mean-log subtracted) + 5 spectral descriptors:
    // [centroid, spread, rolloff(85%), flatness, low/high log-ratio]. All scale-invariant.
    // ------------------------------------------------------------------------------------
    static void extractFeatures(float[] magnitude, int sampleRate, float[] out) {
        final int numBands = DrumClassifierModel.NUM_BANDS;
        final int numBins = DrumClassifierModel.NUM_BINS;
        final int fftSize = DrumClassifierModel.FFT_SIZE;
        final double logEps = DrumClassifierModel.LOG_EPS;
        final int[] edges = DrumClassifierModel.BAND_EDGES_HZ;

        // --- log-band energies, mean-log subtracted; band-power sum kept for flatness ---
        double meanLog = 0;
        double bandPowerSum = 0;
        for (int k = 0; k < numBands; k++) {
            int lo = freqToBin(edges[k], sampleRate, numBins);
            int hi = freqToBin(edges[k + 1], sampleRate, numBins);
            if (hi <= lo) {
                hi = lo + 1;
            }
            if (hi > numBins) {
                hi = numBins;
            }
            double bandPower = 0;
            for (int i = lo; i < hi; i++) {
                bandPower += magnitude[i];
            }
            double logp = Math.log(bandPower + logEps);
            out[k] = (float) logp;
            meanLog += logp;
            bandPowerSum += bandPower;
        }
        meanLog /= numBands;
        for (int k = 0; k < numBands; k++) {
            out[k] = (float) (out[k] - meanLog);
        }

        // --- spectral descriptors over the full spectrum ---
        final double nyq = sampleRate / 2.0;
        // Hz per bin. Exact for 44100/48000 over a 1024 FFT, so hoisting the per-bin division to a
        // multiply is bit-identical to the trainer's `i * sr / fftSize` while killing ~1024 divides.
        final double binToFreq = (double) sampleRate / fftSize;
        double total = 0;
        double weightedFreq = 0;
        int lowBin = freqToBin(500, sampleRate, numBins);
        int highBin = freqToBin(2000, sampleRate, numBins);
        double lowEnergy = 0;
        double highEnergy = 0;
        for (int i = 0; i < numBins; i++) {
            double p = magnitude[i];
            double f = i * binToFreq;
            total += p;
            weightedFreq += f * p;
            if (i < lowBin) {
                lowEnergy += p;
            }
            if (i >= highBin) {
                highEnergy += p;
            }
        }
        double safeTotal = total > 1e-12 ? total : 1e-12;
        double centroid = weightedFreq / safeTotal;

        // spread (2nd pass) + 85% rolloff
        double spreadAccum = 0;
        double rollThreshold = 0.85 * total;
        double running = 0;
        int rollBin = 0;
        boolean rollFound = total <= 1e-12;   // if silent, rolloff bin stays 0 (matches trainer)
        for (int i = 0; i < numBins; i++) {
            double p = magnitude[i];
            double f = i * binToFreq;
            double d = f - centroid;
            spreadAccum += d * d * p;
            if (!rollFound) {
                running += p;
                if (running >= rollThreshold) {
                    rollBin = i;
                    rollFound = true;
                }
            }
        }
        if (rollBin > numBins - 1) {
            rollBin = numBins - 1;
        }
        double spread = Math.sqrt(Math.max(0.0, spreadAccum / safeTotal));
        double rolloff = rollBin * binToFreq;

        // Band-level spectral flatness (geometric/arithmetic mean of the 24 band powers), reusing
        // meanLog so it needs no extra logs — see the matching note in train_drum_classifier.py.
        double bandArithMean = bandPowerSum / numBands;
        double flatness = Math.exp(meanLog) / (bandArithMean + logEps);
        double lowHighRatio = Math.log(lowEnergy + logEps) - Math.log(highEnergy + logEps);

        out[numBands] = (float) Math.min(centroid / nyq, 1.0);
        out[numBands + 1] = (float) Math.min(spread / nyq, 1.0);
        out[numBands + 2] = (float) Math.min(rolloff / nyq, 1.0);
        out[numBands + 3] = (float) flatness;
        out[numBands + 4] = (float) lowHighRatio;
    }

    private static int freqToBin(int freqHz, int sampleRate, int numBins) {
        int b = (int) Math.round(freqHz * 2.0 * numBins / sampleRate);
        if (b < 0) return 0;
        if (b > numBins - 1) return numBins - 1;
        return b;
    }

    // ------------------------------------------------------------------------------------
    // MLP forward: standardize -> [Linear -> ReLU] x2 -> Linear. double accumulation so it matches
    // the trainer's reference numerics regardless of float rounding in the weights.
    // ------------------------------------------------------------------------------------
    private static void forward(float[] rawFeatures, double[] stdFeatScratch,
                                double[] h1, double[] h2, double[] logitsOut) {
        final int dim = DrumClassifierModel.FEATURE_DIM;
        final int n1 = DrumClassifierModel.HIDDEN1;
        final int n2 = DrumClassifierModel.HIDDEN2;
        final int classes = DrumClassifierModel.NUM_CLASSES;
        final float[] mean = DrumClassifierModel.FEATURE_MEAN;
        final float[] std = DrumClassifierModel.FEATURE_STD;

        // Standardize once (not once per hidden unit).
        for (int i = 0; i < dim; i++) {
            stdFeatScratch[i] = (rawFeatures[i] - mean[i]) / std[i];
        }
        for (int j = 0; j < n1; j++) {
            double s = DrumClassifierModel.B1[j];
            for (int i = 0; i < dim; i++) {
                s += stdFeatScratch[i] * DrumClassifierModel.W1[i][j];
            }
            h1[j] = s > 0 ? s : 0;
        }
        for (int j = 0; j < n2; j++) {
            double s = DrumClassifierModel.B2[j];
            for (int i = 0; i < n1; i++) {
                s += h1[i] * DrumClassifierModel.W2[i][j];
            }
            h2[j] = s > 0 ? s : 0;
        }
        for (int c = 0; c < classes; c++) {
            double s = DrumClassifierModel.B3[c];
            for (int j = 0; j < n2; j++) {
                s += h2[j] * DrumClassifierModel.W3[j][c];
            }
            logitsOut[c] = s;
        }
    }

    // ------------------------------------------------------------------------------------
    // Test hooks used by the generated DrumClassifierTest (golden parity vectors).
    // ------------------------------------------------------------------------------------
    static float[] forwardForTest(float[] rawFeatures) {
        double[] out = new double[DrumClassifierModel.NUM_CLASSES];
        forward(rawFeatures, new double[DrumClassifierModel.FEATURE_DIM],
                new double[DrumClassifierModel.HIDDEN1],
                new double[DrumClassifierModel.HIDDEN2], out);
        float[] f = new float[out.length];
        for (int i = 0; i < out.length; i++) {
            f[i] = (float) out[i];
        }
        return f;
    }

    static float[] extractFeaturesForTest(float[] power, int sampleRate) {
        float[] out = new float[DrumClassifierModel.FEATURE_DIM];
        extractFeatures(power, sampleRate, out);
        return out;
    }
}
